### ISSUE TITLE
When tried to load a playable character NPC, the game Crashed

### ISSUE THREAD

**Issue by MarkBlueSNX** [X-Hax/SADXWeightedCharacters#1]
I was trying a mod i was making in the story mode, and when i finished ice cap and tried to go to the Knuckles Fight, then just crashed when i go to the station area from mystic ruins
![Screenshot_2](https://github.com/X-Hax/SADXWeightedCharacters/assets/159034500/a19e99cb-4e31-488a-881e-8613c523ae21)
I know it's the NPCs from the playable characters, because a i tried some events and happen the same thing after the cutscene ends

**Comment by Sora-yx** [comment]
This should be fixed if you grab [the DLL of the last version.](https://github.com/X-Hax/SADXWeightedCharacters/releases/latest)

**Comment by MarkBlueSNX** [comment]
Dude, you're a freaking Genius, Thank You :D
